/**
 * Mandatory reset classification for every database table. Adding a schema
 * table without classifying it makes the reset-catalog coverage test fail.
 */
export const RESETTABLE_TABLES = [
  'department_offices',
  'departments',
  'driver_licence_codes',
  'driver_licence_corrections',
  'driver_licences',
  'driver_professional_authorisations',
  'driver_profiles',
  'emergency_contacts',
  'emergency_overrides',
  'employee_assignments',
  'employee_availability',
  'employee_correction_requests',
  'employee_documents',
  'employee_number_counters',
  'employees',
  'external_driver_assignments',
  'external_driver_licences',
  'external_parties',
  'external_request_drivers',
  'fleet_payment_assignments',
  'fleet_payment_instruments',
  'fleet_payment_providers',
  'fleet_payment_transactions',
  'fuel_receipts',
  'fuel_transactions',
  'generated_documents',
  'import_batches',
  'import_rows',
  'incident_categories',
  'inspection_item_results',
  'inspection_photos',
  'inspection_template_items',
  'inspection_templates',
  'invitation_roles',
  'maintenance_events',
  'notification_deliveries',
  'notification_dismissals',
  'notification_preferences',
  'notification_reads',
  'notifications',
  'offices',
  'programme_reference_sequences',
  'programmes',
  'receipt_field_corrections',
  'regions',
  'reimbursements',
  'request_activities',
  'request_attachments',
  'request_drivers',
  'request_goods_equipment',
  'request_passengers',
  'request_reference_sequences',
  'request_revisions',
  'request_routes',
  'role_assignments',
  'role_delegations',
  'secure_request_sessions',
  'secure_request_verifications',
  'session',
  'share_access_events',
  'share_links',
  'signatory_positions',
  'tenant_holidays',
  'tenant_invitations',
  'tenant_memberships',
  'tenant_readiness_checks',
  'tenant_setup_progress',
  'transport_requests',
  'trip_amendments',
  'trip_authorised_drivers',
  'trip_authorities',
  'trip_authority_passengers',
  'trip_authority_sequences',
  'trip_authority_versions',
  'trip_closures',
  'trip_expenses',
  'trip_incident_sequences',
  'trip_incidents',
  'trip_issues',
  'trip_log_entries',
  'trip_progress_entries',
  'trips',
  'vehicle_allocations',
  'vehicle_categories',
  'vehicle_defects',
  'vehicle_documents',
  'vehicle_inspections',
  'vehicle_odometer_events',
  'vehicle_status_events',
  'vehicles',
  'workflow_actions',
  'workflow_definitions',
  'workflow_instances',
  'workflow_steps',
] as const;

export const PROTECTED_RESET_TABLES = [
  'account',
  'audit_events',
  'payment_submissions',
  'permissions',
  'platform_backups',
  'reset_request_steps',
  'role_permissions',
  'roles',
  'subscription_addons',
  'tenant_branding',
  'tenant_reset_requests',
  'tenant_subscriptions',
  'tenants',
  'user',
  'user_profiles',
  'verification',
] as const;

export const PLATFORM_ONLY_RESET_TABLES = [
  'billing_settings',
  'cms_announcements',
  'cms_content',
  'cms_content_versions',
  'cms_enquiries',
  'cms_faqs',
  'cms_legal_versions',
  'cms_media',
  'cms_site_settings',
  'demo_requests',
  'demo_sandboxes',
  'package_addons',
  'package_entitlements',
  'platform_backup_schedules',
  'subscription_packages',
] as const;

export const RESET_TABLE_CLASSIFICATION = {
  resettable: RESETTABLE_TABLES,
  protected: PROTECTED_RESET_TABLES,
  platformOnly: PLATFORM_ONLY_RESET_TABLES,
} as const;
